services:
  freelance-radar:
    build: .
    container_name: freelance-radar
    restart: unless-stopped
    env_file: app.env
    networks:
      - fr-net
    volumes:
      - ./kwork_token.json:/app/.kwork_token.json
    depends_on:
      - fr-postgres

  fr-postgres:
    image: postgres:16-alpine
    container_name: fr-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: freelance_radar
      POSTGRES_USER: fr_user
      POSTGRES_PASSWORD: fr_pass_2026
    volumes:
      - fr-postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - fr-net
    ports:
      - "127.0.0.1:5433:5432"

networks:
  fr-net:
    driver: bridge

volumes:
  fr-postgres-data:
